name: Governance
on:
  pull_request:
  push:
    branches: [master, main]
permissions:
  contents: read
jobs:
  governance:
    name: Governance
    uses: AIAllTheThingz/Engineering-Standards/.github/workflows/governance-ci-reusable.yml@6df785074523a9b59566ac80410891552fe5eb4d
    with:
      project-path: .
      governance-version: 1.1.0
