name: Governance
on:
  pull_request:
  push:
    branches: [master, main]
permissions:
  contents: read
jobs:
  governance:
    uses: AIAllTheThingz/Engineering-Standards/.github/workflows/governance-ci-reusable.yml@5450976a4cf02661854df24f4427082242821edd
    with:
      project-path: .
      governance-version: 1.1.0
