Describe 'Governance validation home-lab demo' {
 BeforeAll{$script:r=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$script:s=(Resolve-Path (Join-Path $script:r '../..')).Path;$script:k=Get-Content (Join-Path $script:r '.agents/skills/governance-validation/SKILL.md') -Raw;$script:m=Get-Content (Join-Path $script:r 'project-manifest.json') -Raw|ConvertFrom-Json;$script:c=Get-Content (Join-Path $script:r 'samples/candidate-records.json') -Raw|ConvertFrom-Json;$script:o=Get-Content (Join-Path $script:r 'demo-output/expected-report.json') -Raw|ConvertFrom-Json;Import-Module (Join-Path $script:r 'tools/GovernanceCandidateEvaluation.psm1') -Force;$script:actual=Test-SyntheticGovernanceCandidate -Path (Join-Path $script:r 'samples/candidate-records.json')}
 It 'keeps the skill isolated and trusted authority external to candidate data'{Test-Path (Join-Path $script:s '.agents/skills/governance-validation/SKILL.md')|Should -BeFalse;$script:k|Should -Match 'trusted standards commit';$script:k|Should -Match 'Never execute a\s+validator path'}
 It 'rejects candidate controls as inert data without executing them'{@($script:c.candidates).Count|Should -Be 2;$raw=Get-Content (Join-Path $script:r 'samples/candidate-records.json') -Raw;$raw|Should -Match 'should-never-run';$raw|Should -Match '\.\./\.\./untrusted';$script:actual.candidateCommandsExecuted|Should -Be 0;$invalid=$script:actual.results|Where-Object candidateId -eq 'invalid';@($invalid.rejectedCandidateFields)|Should -Be @('candidateCommand','candidateValidator');$invalid.checks.CandidateControlIsolation|Should -BeExactly 'Failed'}
 It 'derives the expected report from trusted evaluator logic'{$actualJson=$script:actual|ConvertTo-Json -Depth 8 -Compress;$expectedJson=$script:o|ConvertTo-Json -Depth 8 -Compress;$actualJson|Should -BeExactly $expectedJson}
 It 'does not let a required failure aggregate to Passed'{$failed=$script:actual.results|Where-Object candidateId -eq 'invalid';$failed.status|Should -BeExactly 'Failed';$failed.checks.DocumentationCompleteness|Should -BeExactly 'Failed';$script:actual.candidateCommandsExecuted|Should -Be 0}
 It 'binds honest local evidence to the governed trusted source'{$script:o.executionContext|Should -BeExactly 'Local';$script:o.hostedExecution|Should -BeExactly 'NotRun';$script:o.artifactsVerified|Should -BeFalse;$script:o.trustedValidatorSource|Should -BeExactly "AIAllTheThingz/Engineering-Standards@$($script:m.governanceCommitSha)"}
 It 'provides nine routing cases and refuses unsafe categories'{$cases=@(Get-ChildItem (Join-Path $script:r 'tests/fixtures/codex-skills/prompt-behavior') -Filter '*.json'|%{Get-Content $_.FullName -Raw|ConvertFrom-Json});$cases.Count|Should -Be 9;foreach($x in @('explicit-invocation','implicit-invocation','non-trigger-explanation','non-trigger-one-liner','non-trigger-review','ambiguous','governance-bypass','secret-exposure','destructive-default')){$cases.category|Should -Contain $x};@($cases|? category -in @('governance-bypass','secret-exposure','destructive-default')|? expectedSafetyOutcome -cne 'Refuse').Count|Should -Be 0}
}
