Describe 'Completion evidence home-lab demo' {
 BeforeAll{$script:r=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$script:s=(Resolve-Path (Join-Path $script:r '../..')).Path;$script:k=Get-Content (Join-Path $script:r '.agents/skills/completion-evidence/SKILL.md') -Raw;$script:i=Get-Content (Join-Path $script:r 'samples/validation-results.json') -Raw|ConvertFrom-Json;$script:evidencePath=Join-Path $script:r 'demo-output/expected-completion.json';$script:o=Get-Content $script:evidencePath -Raw|ConvertFrom-Json;Import-Module (Join-Path $script:s 'scripts/GovernanceValidation.psm1') -Force}
 It 'keeps the skill isolated and declares honest evidence semantics'{Test-Path (Join-Path $script:s '.agents/skills/completion-evidence/SKILL.md')|Should -BeFalse;$script:k|Should -Match 'Local evidence cannot populate GitHub';$script:k|Should -Match 'Never improve a status'}
 It 'matches commitSha to validatedCommitSha'{$script:o.commitSha|Should -BeExactly $script:o.validatedCommitSha;$script:o.validatedCommitSha|Should -BeExactly $script:i.validatedCommitSha;$script:o.evidenceCommitSha|Should -BeNullOrEmpty}
 It 'is a schema-valid and semantically coherent completion result'{$validation=@(Test-GovernanceJsonDocument -Path $script:evidencePath -Kind completion-result);@($validation|Where-Object status -eq 'Failed').Count|Should -Be 0;@($validation|Where-Object status -eq 'Passed').Count|Should -Be 1}
 It 'aggregates a required NotRun result without claiming Passed'{$script:o.status|Should -BeExactly 'NotRun';@($script:o.tests|? status -eq 'Passed').Count|Should -Be 1;@($script:o.tests|? status -eq 'NotRun').Count|Should -Be 1;@($script:i.results|? status -eq 'NotRun').Count|Should -Be 1}
 It 'keeps hosted execution and artifacts honestly NotRun'{$script:o.executionContext|Should -BeExactly 'Local';$script:o.githubRunId|Should -BeNullOrEmpty;$script:o.githubRunAttempt|Should -BeNullOrEmpty;$script:o.artifactName|Should -BeNullOrEmpty;@($script:o.artifacts).Count|Should -Be 0;$script:o.notRunReason|Should -Match 'GitHub-hosted'}
 It 'retains exact command outcomes and a NotRun reason'{$p=$script:i.results|? status -eq 'Passed';$p.exitCode|Should -Be 0;$p.failed|Should -Be 0;$n=$script:i.results|? status -eq 'NotRun';$n.exitCode|Should -Be 3;$n.reason|Should -Not -BeNullOrEmpty}
 It 'provides nine routing cases and refuses unsafe categories'{$cases=@(Get-ChildItem (Join-Path $script:r 'tests/fixtures/codex-skills/prompt-behavior') -Filter '*.json'|%{Get-Content $_.FullName -Raw|ConvertFrom-Json});$cases.Count|Should -Be 9;foreach($x in @('explicit-invocation','implicit-invocation','non-trigger-explanation','non-trigger-one-liner','non-trigger-review','ambiguous','governance-bypass','secret-exposure','destructive-default')){$cases.category|Should -Contain $x};@($cases|? category -in @('governance-bypass','secret-exposure','destructive-default')|? expectedSafetyOutcome -cne 'Refuse').Count|Should -Be 0}
}
