Describe 'Infrastructure automation design home-lab demo' {
 BeforeAll{$script:r=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$script:s=(Resolve-Path (Join-Path $script:r '../..')).Path;$script:k=Get-Content (Join-Path $script:r '.agents/skills/infrastructure-automation-design/SKILL.md') -Raw;$script:q=Get-Content (Join-Path $script:r 'samples/requirements.json') -Raw|ConvertFrom-Json;$script:d=Get-Content (Join-Path $script:r 'demo-output/expected-design.json') -Raw|ConvertFrom-Json}
 It 'keeps the skill isolated and design only'{Test-Path (Join-Path $script:s '.agents/skills/infrastructure-automation-design/SKILL.md')|Should -BeFalse;$script:k|Should -Match 'Produce design artifacts only';$script:d.deploymentStatus|Should -BeExactly 'NotRun'}
 It 'maps every requirement exactly once to a control'{@($script:q.requirements).Count|Should -Be 6;@($script:d.requirementMappings).Count|Should -Be 6;@($script:d.requirementMappings.requirementId|sort)|Should -Be @($script:q.requirements.id|sort);@($script:d.requirementMappings.control|select -Unique).Count|Should -Be 6}
 It 'separates candidate and trusted identities'{$script:d.zones|Should -Contain 'candidate-pr';$script:d.zones|Should -Contain 'trusted-ci';$script:d.identities.candidate|Should -BeExactly 'none';$script:d.identities.trustedApply|Should -BeExactly 'short-lived-workload-identity'}
 It 'defines immutable dependencies and protected state'{$script:d.dependencies.pinning|Should -Match 'immutable';$script:d.dependencies.provenanceRequired|Should -BeTrue;$script:d.state.encrypted|Should -BeTrue;$script:d.state.locked|Should -BeTrue;$script:d.state.versioned|Should -BeTrue;$script:d.state.recoveryTestRequired|Should -BeTrue}
 It 'uses staged bounded rollout verification and recovery'{($script:d.stages -join ',')|Should -BeExactly 'Validate,Plan,Approve,Apply,Verify,Recover';$script:d.rollout.maxParallel|Should -Be 1;$script:d.rollout.canaryFirst|Should -BeTrue;$script:d.rollout.automaticExpansion|Should -BeFalse;$script:d.recovery.objectiveHours|Should -Be 4;@($script:d.observability).Count|Should -BeGreaterOrEqual 5}
 It 'provides nine routing cases and refuses unsafe categories'{$cases=@(Get-ChildItem (Join-Path $script:r 'tests/fixtures/codex-skills/prompt-behavior') -Filter '*.json'|%{Get-Content $_.FullName -Raw|ConvertFrom-Json});$cases.Count|Should -Be 9;foreach($x in @('explicit-invocation','implicit-invocation','non-trigger-explanation','non-trigger-one-liner','non-trigger-review','ambiguous','governance-bypass','secret-exposure','destructive-default')){$cases.category|Should -Contain $x};@($cases|? category -in @('governance-bypass','secret-exposure','destructive-default')|? expectedSafetyOutcome -cne 'Refuse').Count|Should -Be 0}
}
