name: Governance
on:
  pull_request:
  push:
    branches: [master, main]
permissions:
  contents: read
jobs:
  governance:
    name: Governance
    uses: AIAllTheThingz/Engineering-Standards/.github/workflows/governance-ci-reusable.yml@b6c85e1deb4685791db6cd8decd915a5f7477600
    with:
      project-path: .
      governance-version: 1.1.0
